version: '3.0'
services:
  nginx:
    image: nginx:latest
    ports:
      - 900:80
    volumes:
      - .:/var/www/rest
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - backend

  php:
    container_name: rest_web
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/rest
    links:
      - mysql
    networks:
      - backend
    environment:
        DB_DATABASE: ${DB_DATABASE}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: rest_mysql
    environment:
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    env_file:
        - ./.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - backend

networks:
  backend: